# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

version: "3.9"

networks:
    local:
        driver: bridge

services:

    yadisk-converter:
        container_name : yadisk-converter
        image          : yadisk-converter:latest
        restart        : always
        build          : .

        networks:
            - local
        ports:
            - 5000:5000
        volumes:
            - .:/usr/src/yadisk-converter